### ISSUE TITLE
Not working on Anki's latest 2.1.25 update :( Please update it

### ISSUE THREAD

**Issue by youknowme11** [Arthur-Milchior/anki-copy-note#13]
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.25 (898801eb) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-05-02 19:22:09

**Caught exception:
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Anki2\addons21\1566928056\copyNote.py", line 65, in <lambda>
    a.triggered.connect(lambda: copyNotes(browser.selectedNotes()))
  File "C:\Users\USER\AppData\Roaming\Anki2\addons21\1566928056\copyNote.py", line 52, in copyNotes
    copyNote(nid)
  File "C:\Users\USER\AppData\Roaming\Anki2\addons21\1566928056\copyNote.py", line 81, in copyNote
    copyCard(card, note)
  File "C:\Users\USER\AppData\Roaming\Anki2\addons21\1566928056\copyNote.py", line 98, in copyCard
    card.flush()
  File "lib\site-packages\anki\cards.py", line 107, in flush
  File "lib\site-packages\anki\rsbackend.py", line 507, in update_card
  File "lib\site-packages\anki\rsbackend.py", line 257, in _run_command
anki.rsbackend.StringError: InvalidInput { info: "missing card" }**

**Comment by youknowme11** [comment]
BTW this is one of my all-time fave addons

**Comment by Arthur-Milchior** [comment]
Thanks for the bug report.
I'm surprised that anyone need to copy enough card for this to be their preferred add-ons. I'll take a look at it

**Comment by Arthur-Milchior** [comment]
Please update

**Comment by youknowme11** [comment]
Lovely stuff. Cheers for the prompt fix!
