### ISSUE TITLE
Cannot copy

### ISSUE THREAD

**Issue by honis56** [Arthur-Milchior/anki-copy-note#26]
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2021-02-17 09:03:06

Caught exception:
Traceback (most recent call last):
  File "C:\Users\Holger\AppData\Roaming\Anki2\addons21\1566928056\copyNote.py", line 65, in <lambda>
    a.triggered.connect(lambda: copyNotes(browser.selectedNotes()))
  File "C:\Users\Holger\AppData\Roaming\Anki2\addons21\1566928056\copyNote.py", line 52, in copyNotes
    copyNote(nid)
  File "C:\Users\Holger\AppData\Roaming\Anki2\addons21\1566928056\copyNote.py", line 83, in copyNote
    note.flush()
  File "anki\notes.py", line 68, in flush
  File "anki\rsbackend_gen.py", line 344, in update_note
  File "anki\rsbackend.py", line 267, in _run_command
anki.rsbackend.NotFoundError

**Comment by Arthur-Milchior** [comment]
This should now be corrected. Can you confirm?
