### ISSUE TITLE
Error: Expected 15 fields found 16

### ISSUE THREAD

**Issue by myarcana** [Arthur-Milchior/anki-copy-note#45]
This error appears when I right-click a note in the browser and click `Note Copy`, or when I press Cmd-C:

```
Traceback (most recent call last):
  File "~/Library/Application Support/Anki2/addons21/1566928056/copyNote.py", line 67, in <lambda>
    a.triggered.connect(lambda: copyNotes(browser))
  File "~/Library/Application Support/Anki2/addons21/1566928056/copyNote.py", line 54, in copyNotes
    copyNote(nid)
  File "~/Library/Application Support/Anki2/addons21/1566928056/copyNote.py", line 78, in copyNote
    new_note, new_cards = add_note_with_id(note, nid if getUserOption("Preserve creation time", True) else None)
  File "~/Library/Application Support/Anki2/addons21/1566928056/new_note_id.py", line 10, in add_note_with_id
    mw.col.add_note(note, 1)
  File "anki/collection.py", line 373, in add_note
  File "anki/_backend/generated.py", line 303, in add_note
  File "anki/_backend/__init__.py", line 131, in _run_command
anki.errors.InvalidInput: Invalid input: ⁨note has 15 fields, expected 16⁩
```

Also, there is no `Note Copy` item in the Edit menu.

**Comment by HappyKap** [comment]
This same error with me...

except there is copy note in edit note browser menu
