### ISSUE TITLE
Export bug / retrieving lost notes

### ISSUE THREAD

**Issue by Arthur-Milchior** [Arthur-Milchior/anki-copy-note#6]
This is the following of the thread https://github.com/Arthur-Milchior/anki-unique-GUID/issues/1 by @galantra
unique-GUID add-on doesn't exists anymore, I merged it into copy note.

**Comment by Arthur-Milchior** [comment]
Hi @Galantra

The code on github should correct the problem you have. Since you're a dev, I assume that you know how to use code directly from github. If it is the case, can you try this code and see whether it fixes your problem. If you confirm that it is the case, then I'll update the add-on on ankiweb.

Technically, once you have the new code, and restarted anki, you can import again the deck and anki will detect which cards are new and which ones are already imported. Technically, it'll consider both GUID and NID to determines copies. So you should have your missing card back.

**Comment by galantra** [comment]
I will try to test it.
In fact, I am not a software developer. I am a student of a humanities subject. I have comparatively superficial knowledge of computers. Therefore, I describe what I'm going to do (so you can see if I am doing something wrong):

1. Download the github repository.
2. Replace the files in my add-on folder with the correspondingly named files from the download.
3. Import my decks.

**Comment by Arthur-Milchior** [comment]
That's it. 
You've got a pro github account; so I must admit I'm surprised that you're not more used than that to programming.

**Comment by galantra** [comment]
I have it due to the [GitHub Student Developer Pack](https://education.github.com/pack#offers). It's the largest single gift I ever got and everyone should check it out.

Now, when I restarted Anki, this appeared:
![grafik](https://user-images.githubusercontent.com/52420923/66275596-71917600-e88a-11e9-8414-872296733061.png)
Importing the old decks did not retrieve the lost notes.

**Comment by Arthur-Milchior** [comment]
Corrected. Please update the file copyNote.py

**Comment by galantra** [comment]
Import returns:
```
Import failed.
Traceback (most recent call last):
  File "aqt\importing.py", line 339, in importFile
  File "anki\importing\apkg.py", line 39, in run
  File "anki\importing\anki2.py", line 28, in run
  File "anki\importing\anki2.py", line 53, in _import
  File "anki\importing\anki2.py", line 98, in _importNotes
  File "C:\Users\user\AppData\Roaming\Anki2\addons21\1566928056\copyNote.py", line 124, in _uniquifyNote
    destId, destGuid, destMod, destMid = self._notes[note[GUID]]
ValueError: not enough values to unpack (expected 4, got 3)
```

**Comment by Arthur-Milchior** [comment]
This is corrected. Sorry, I thought I did warn you taht it is the case.

**Comment by galantra** [comment]
`Import failed.
Traceback (most recent call last):
  File "aqt\importing.py", line 339, in importFile
  File "anki\importing\apkg.py", line 39, in run
  File "anki\importing\anki2.py", line 28, in run
  File "anki\importing\anki2.py", line 53, in _import
  File "anki\importing\anki2.py", line 98, in _importNotes
  File "C:\Users\Jo\AppData\Roaming\Anki2\addons21\1566928056\copyNote.py", line 131, in _uniquifyNote
    note[GUID] += 1
TypeError: must be str, not int
`

**Comment by galantra** [comment]
`Import failed.
Traceback (most recent call last):
  File "aqt\importing.py", line 339, in importFile
  File "anki\importing\apkg.py", line 39, in run
  File "anki\importing\anki2.py", line 28, in run
  File "anki\importing\anki2.py", line 53, in _import
  File "anki\importing\anki2.py", line 98, in _importNotes
  File "C:\Users\user\AppData\Roaming\Anki2\addons21\1566928056\copyNote.py", line 131, in _uniquifyNote
    note[GUID] += 1
TypeError: must be str, not int
`

**Comment by galantra** [comment]
So, according to the advice I was given by internet research, line 131 should be:`
    str(note[GUID] += 1)`
But I am skeptical if make the code function as intended.

**Comment by galantra** [comment]
Dear Arthur,
I would be grateful if you could kindly give a very brief update. Do you intend to bring this add-on to functionality?
The reason I'm asking is because I'm preparing for a final exam which encompasses really an unreasonable scope. I cannot exaggerate it's importance in determining my professional future (we do not have smaller, regular exams). (You see, I am anxious about it).
Therefore, I have to either 1. retrieve my lost notes or 2. find out what is missing and "piece it together" again. I would like to plan what I should do. Right now, I'm in a state of limbo.

**Comment by Arthur-Milchior** [comment]
my bad, it slept out of my mind. Yes, I didn't plan to stop repairing it. I'm going to take a look at it right now

**Comment by Arthur-Milchior** [comment]
This bug is corrected.
The problem is that it's quite hard for me to test it as I don't have the bug. At least because testing it would need for me to create a buggy deck, import it and then try to correct. Which is not easy.

Anyway, don't hesitate to write me at arthur@milchior.fr if there is a problem and I forget to answer.
I had A LOT of github message recently, because I contributed to ankidroid, and I guess your message was lost by accident with all other messages.

**Comment by Arthur-Milchior** [comment]
Oh, and by the way, good luck for your exam.

**Comment by galantra** [comment]
Thanks, I appreciate it!

I guessed you have a lot of important work to do and I certainly do not want to annoy you.

I can do the testing.

This is the error I got with the recent code:
```
Import failed.
Traceback (most recent call last):
  File "aqt\importing.py", line 339, in importFile
  File "anki\importing\apkg.py", line 39, in run
  File "anki\importing\anki2.py", line 28, in run
  File "anki\importing\anki2.py", line 53, in _import
  File "anki\importing\anki2.py", line 98, in _importNotes
  File "C:\Users\Jo\AppData\Roaming\Anki2\addons21\1566928056\copyNote.py", line 131, in _uniquifyNote
    note[GUID] = guit64()
NameError: name 'guit64' is not defined

```
I guessed it was a typo, so I changed "guit" to "guid".

After this change, this is now the error:

```
Import failed.
Traceback (most recent call last):
  File "aqt\importing.py", line 339, in importFile
  File "anki\importing\apkg.py", line 39, in run
  File "anki\importing\anki2.py", line 28, in run
  File "anki\importing\anki2.py", line 53, in _import
  File "anki\importing\anki2.py", line 98, in _importNotes
  File "C:\Users\user\AppData\Roaming\Anki2\addons21\1566928056\copyNote.py", line 132, in _uniquifyNote
    if not firstBug:
UnboundLocalError: local variable 'firstBug' referenced before assignment

```

**Comment by Arthur-Milchior** [comment]
In fact, if you share your deck with me, it'll allow me to test easily importing and debug it myself. I lack a bugged deck, but I'm realizing you have got one

**Comment by Arthur-Milchior** [comment]
Anyway, this one bug is corrected

**Comment by galantra** [comment]
Good job, the decks have been imported. Now I see some of my "old acquaintances" again, haha.

Merci beaucoup :)

**Comment by Arthur-Milchior** [comment]
Great.

Sorry for being the creator of this bug and taking so much time to correct
it

**Comment by galantra** [comment]
Well you for creating such useful add-ons in the first place! You are a great developer.
