### ISSUE TITLE
Add-on fails to load (Anki 2.1.0beta36, Ubuntu 18.04)

### ISSUE THREAD

**Issue by willbradshaw** [Arthur-Milchior/anki-copy-note#9]
Hi Arthur,

When I try to load Anki with this add-on, I get this error:

"An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading 'Copy notes':
Traceback (most recent call last):
  File "/usr/share/anki/aqt/addons.py", line 57, in loadAddons
    __import__(dir)
  File "/home/will/.local/share/Anki2/addons21/1566928056/__init__.py", line 1, in <module>
    from . import copyNote, debug
  File "/home/will/.local/share/Anki2/addons21/1566928056/copyNote.py", line 38, in <module>
    from .config import getUserOption
  File "/home/will/.local/share/Anki2/addons21/1566928056/config.py", line 54, in <module>
    mw.addonManager.setConfigUpdatedAction(__name__,update)
AttributeError: 'AddonManager' object has no attribute 'setConfigUpdatedAction'"

I'm running Anki Version 2.1.0beta36 (Qt 5.9.5 PyQt 5.10.1) on Ubuntu 18.04.3 LTS.

Thanks!
Will

**Comment by Arthur-Milchior** [comment]
You've got a very old version of anki. 2.1.0beta36. Anki is not beta anymore. Can you please install anki directly from the website ? I know that ubuntu lags a lot when it comes to Anki version. I believe that this is the cause of the problem, and I don't want to maintain compatibility with older versions
